[package]
name = "Synapse"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
derive_more = { version = "1", features = ["full"] }
dotenvy = "0.15.7"
log = "0.4.22"
rig-core = "0.6.0"
serde = "1.0.216"
serde_json = "1.0.134"
